server {
    listen       80;
    server_name  localhost;

    # 1. 部署 React 前端页面
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. 部署离线地图瓦片静态服务 (支持外部挂载至 /usr/share/nginx/html/tiles)
    location /tiles/ {
        root   /usr/share/nginx/html;
        autoindex on;
        expires 30d;
        access_log off;
        # 支持跨域访问
        add_header Access-Control-Allow-Origin *;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
